#!/usr/bin/env bash
# gen-cli-reference.sh — generate docs/cli-reference.md from each tool's --help.
#
# The single source of truth for flags is each tool's own usage(); this just
# collects them so someone browsing the repo can see what every command does.
# Re-run (make cli-reference) after changing a tool's flags.
#
# Usage: gen-cli-reference.sh [--check] [-n] [-h|--help] [-V|--version]
#   --check        Verify docs/cli-reference.md is current; write nothing, exit 1
#                  if stale (used by `make check`).
#   -n, --dry-run  Print the generated reference to stdout instead of writing it.
#
# Exit: 0 ok; 1 stale (with --check); 2 usage.
set -Eeuo pipefail
set -o errtrace
shopt -s inherit_errexit 2>/dev/null || true
IFS=$'\n\t'

readonly APP_NAME="gen-cli-reference"
readonly APP_VERSION="0.1.0"
LOG_TAG="(${APP_NAME})"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

require_bash 4

REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
readonly REPO_ROOT
readonly OUT="${REPO_ROOT}/docs/cli-reference.md"

# User-facing commands to document, in reading order.
TOOLS=(
  tools/ados-ollama
  tools/ados-ollama-doctor
  scripts/setup-ollama.sh
  scripts/install-ados.sh
  tools/gen-opencode-config
  tools/ados-sandbox
  tools/ados-sandbox-macos
  scripts/setup-dev.sh
)

CHECK=false

render() {
  cat <<'EOF'
<!-- Generated by `make cli-reference` (scripts/gen-cli-reference.sh) from each
     tool's --help. Do not edit by hand; re-run after changing a tool's flags. -->

# CLI reference

Every user-facing command in this toolkit. Each block is the tool's own `--help`
output, so this file stays in sync with the code (`make check` fails if it drifts).
EOF
  local t
  for t in "${TOOLS[@]}"; do
    # shellcheck disable=SC2016  # backticks are literal markdown, not a subshell
    printf '\n## `%s`\n\n```text\n' "${t}"
    (cd "${REPO_ROOT}" && bash "${t}" --help)
    printf '```\n'
  done
}

usage() {
  cat <<EOF
Usage: ${APP_NAME} [options]

Generate docs/cli-reference.md from every tool's --help output.

Options:
  --check        Verify the committed reference is current (exit 1 if stale)
  -n, --dry-run  Print to stdout instead of writing the file
  -h, --help     Show this help
  -V, --version  Show version
EOF
}

main() {
  while (($#)); do
    case "$1" in
      -h | --help)
        usage
        exit 0
        ;;
      -V | --version)
        printf '%s %s\n' "${APP_NAME}" "${APP_VERSION}"
        exit 0
        ;;
      --check) CHECK=true ;;
      -n | --dry-run) DRY_RUN=true ;;
      *) die "Unknown option: $1" ;;
    esac
    shift
  done

  if [[ "${DRY_RUN}" == "true" ]]; then
    render
    return 0
  fi

  if [[ "${CHECK}" == "true" ]]; then
    local tmp
    tmp="$(mktemp)"
    render >"${tmp}"
    if [[ -f "${OUT}" ]] && cmp -s "${tmp}" "${OUT}"; then
      rm -f "${tmp}"
      log_info "cli-reference is current"
      return 0
    fi
    rm -f "${tmp}"
    log_err "docs/cli-reference.md is stale — run: make cli-reference"
    return 1
  fi

  mkdir -p "$(dirname "${OUT}")"
  render >"${OUT}"
  log_info "wrote ${OUT}"
}

if [[ -z "${BASH_SOURCE[0]:-}" || "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
